# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  # see: https://docs.djangoproject.com/en/dev/faq/install/#faq-python-version-support
  - "3.4"
  - "3.5"

install:
  - pip install --upgrade pip
  - pip install .
  - pip install -r requirements/unittest_installation.txt
  - pip freeze

script:
  - coverage run ./setup.py test

after_success:
  - coveralls

notifications:
  irc: "irc.freenode.org#pylucid"