# Config file for automatic testing at travis-ci.org
#
# https://docs.travis-ci.com/user/languages/python/
# https://docs.travis-ci.com/user/reference/overview/
# https://docs.travis-ci.com/user/environment-variables/
#
# Note:
# We currently can't check the boot process with different python versions :(
# The created virtualenv doesn't work: see:
# https://github.com/travis-ci/travis-ci/issues/8589
#
# setup script will be created in /home/travis/virtualenv/python3.6.4/bin/
# and not in created virtualenv in /home/travis/PyLucid-env/bin/
# e.g.:
# https://travis-ci.org/jedie/PyLucid/jobs/346286453#L580-L598


sudo: false
dist: trusty

language: python

python:
  - "3.6"

matrix:
  include:
    - env: BOOT_MODE=boot
    - env: BOOT_MODE=boot_developer

branches:
  only:
  - develop

before_install:
  # Work-a-round for https://github.com/travis-ci/travis-ci/issues/8589
  - ls /opt/python/
  - /opt/python/3.6/bin/python --version

install:
  - echo $BOOT_MODE
  - /opt/python/3.6/bin/python pylucid/pylucid_boot.py $BOOT_MODE ~/PyLucid-env

  - cd ~/PyLucid-env
  - ls -la bin
  - source bin/activate

  - cp -Rfv ${TRAVIS_BUILD_DIR} ~/PyLucid-env/src/pylucid
  - cd ~/PyLucid-env/src/pylucid
  - pip install -e .
  - pip install -r pylucid/requirements/test_requirements.txt

script:
  - cd ~/PyLucid-env/src/pylucid
  - pylucid_admin pip_freeze
  - pylucid_admin pytest

after_success:
    # https://github.com/codecov/codecov-bash
    - bash <(curl -s https://codecov.io/bash)
    - coveralls

after_script:
  - rm -Rf ~/PyLucid-env
