# Config file for automatic testing at travis-ci.org

sudo: required
dist: trusty
# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
group: deprecated-2017Q4
language: python

python:
  - "3.5"
  - "3.6"
  - "pypy3"

install:
  - python --version

  - python pylucid/pylucid_boot.py boot ~/PyLucid-env

  - cd ~/PyLucid-env
  - ls -la bin
  - source bin/activate

  - pylucid_admin pip_freeze
  - pylucid_admin pytest
