# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install ."
  - "pip install -r requirements/unittest_installation.txt"

script:
  - python setup.py test

after_success:
  coveralls
