# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  # https://docs.djangoproject.com/en/dev/faq/install/#faq-python-version-support
  # https://docs.travis-ci.com/user/languages/python/
  - "3.4"
  - "3.5"

install:
  - travis_retry pip install --upgrade pip
  - travis_retry pip install .
  - travis_retry pip install -r requirements/normal_installation.txt
  - travis_retry pip install -r requirements/unittest_requirements.txt
  - travis_retry pip freeze

script:
   - ./setup.py test

after_success:
  - travis_retry coveralls

notifications:
  irc: "irc.freenode.org#pylucid"
